# `r fontawesome::fa("calendar-alt")` Schedule. {#sec-schedule}

`r fontawesome::fa("credit-card")` ARF1, Spring 2024. Room  4403 A, 16:00 – 17:30. Zoom [https://us02web.zoom.us/j/85044414325](https://us02web.zoom.us/j/85044414325)

## `r fontawesome::fa("battery-quarter")` Part 1.

**Session 1. `r fontawesome::fa("handshake")` Thursday, 11 January.**

- Reading. Course syllabus (this document).
- Activity. Welcome and introduction to the course.
- Activity. Set up your free DataCamp and Deepnote accounts. You should have received invitations in your UDEM student email.
- Activity. Define your group of no more than 4 members. You should have received an invitation in your UDEM student email.

**Session 2. Monday, 15 January.**
**Session 3. Thursday, 18 January.**
**Session 4. Monday, 22 January.**
**Session 5. Thursday, 25 January.**
**Session 6. Monday, 29 January.**
**Session 7, Zoom. Thursday, 1 February.**
**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 5 February.**
**Session 8. Thursday, 8 February.**
**Session 9. Monday, 12 February.**
**Session 10, Zoom. `r fontawesome::fa("heart", fill = "red")` Thursday, 15 February.**
**Session 11. Monday, 19 February.**
**Session 12, Zoom. Thursday, 22 February.**
## `r fontawesome::fa("battery-half")` Part 2.
**Session 13. Monday, 26 February.**
**Session 14. Thursday, 29 February.**
**Session 15, Zoom. Monday, 4 March.**
**Session 16. `r fontawesome::fa("female")` Thursday, 7 March.**
**Session 17. Monday, 11 March.**
**Session 18, Zoom. $\pi$ Thursday, 14 March.**
**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 18 March.**
**Session 19. Thursday, 21 March.**
**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 25 March.**
**Holiday. `r fontawesome::fa("umbrella-beach")` Thursday, 28 March.**
**Session 20, Zoom. Monday, 1 April.**
**Session 21, Zoom. Thursday, 4 April.**
## `r fontawesome::fa("battery-three-quarters")` Part 3.
**Session 22. Monday, 8 April.**
**Session 23. Thursday, 11 April.**
**Session 24. Monday, 15 April.**
**Session 25. Thursday, 18 April.**
**Session 26. Monday, 22 April.**
**Session 27, Zoom. Thursday, 25 April.**
**Session 28, Zoom. `r fontawesome::fa("children")` Monday, 29 April.**
**Session 29. `r fontawesome::fa("jedi-order")` Thursday, 2 May.**
**Session 30. Monday, 6 May.**
**Session 31, Zoom. `r fontawesome::fa("female")` Thursday, 9 May.**
## `r fontawesome::fa("battery-full")` The end.

**Final exam, Zoom. Thursday, 23 May, 16:00 – 18:00.**

- Graded. $E_F$ Instructions in Blackboard.
